import type { Metadata } from "next"
import Link from "next/link"
import { Geist, Geist_Mono } from "next/font/google"
import { getServerSession } from "next-auth"

import { AppProviders } from "@/components/providers/app-providers"
import { SessionMenuLink } from "@/components/ui/session-menu-link"
import { authConfig } from "@/app/api/auth/[...nextauth]/route"
import { Toaster } from "@/components/ui/toaster"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders session={session}>
          <div className="min-h-screen bg-background text-foreground">
            <header className="border-b bg-card/40 backdrop-blur">
              <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4">
                <Link href="/" className="text-base font-semibold tracking-tight">
                  KnowFlow AI
                </Link>
                <div className="flex items-center gap-4">
                  <SessionMenuLink />
                </div>
              </div>
            </header>
            {children}
          </div>
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}